<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Procurement Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            color: #333;
        }

        .header {
            width: 100%;
            text-align: center;
            margin-bottom: 20px;
            border-bottom: 2px solid #22c55e;
            padding-bottom: 10px;
        }

        .logo {
            max-width: 150px;
            margin-bottom: 10px;
        }

        .report-title {
            font-size: 20px;
            font-weight: bold;
            text-transform: uppercase;
            color: #1f2937;
        }

        .report-meta {
            font-size: 12px;
            color: #6b7280;
            margin-top: 5px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 15px;
        }

        th,
        td {
            border: 1px solid #e5e7eb;
            padding: 8px 10px;
            text-align: left;
        }

        th {
            background-color: #f3f4f6;
            font-weight: bold;
            color: #374151;
        }

        tr:nth-child(even) {
            background-color: #f9fafb;
        }

        .status {
            text-transform: uppercase;
            font-size: 10px;
            font-weight: bold;
        }

        .footer {
            margin-top: 30px;
            text-align: right;
            font-size: 10px;
            color: #9ca3af;
        }
    </style>
</head>

<body>

    <div class="header">
        @if(file_exists(public_path('images/logo.svg')))
            <img src="{{ public_path('images/logo.svg') }}" class="logo" alt="Company Logo">
        @endif
        <div class="report-title">Procurement Report</div>
        <div class="report-meta">
            Generated on: {{ now()->format('F d, Y h:i A') }}<br>
            Filter: {{ $filterLabel }}
            @if($projectName)
                <br>Project: {{ $projectName }}
            @endif
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Project</th>
                <th>Requester</th>
                <th>Date</th>
                <th>Status</th>
                <th>Items Count</th>
            </tr>
        </thead>
        <tbody>
            @foreach($requests as $req)
                <tr>
                    <td>#{{ $req->id }}</td>
                    <td>{{ $req->project ? $req->project->name : 'N/A' }}</td>
                    <td>{{ $req->user ? $req->user->name : 'N/A' }}</td>
                    <td>{{ $req->created_at->format('Y-m-d') }}</td>
                    <td><span class="status">{{ $req->status }}</span></td>
                    <td>{{ $req->items->count() }}</td>
                </tr>
            @endforeach
            @if($requests->isEmpty())
                <tr>
                    <td colspan="6" style="text-align: center; padding: 20px;">No procurement requests found for this
                        filter.</td>
                </tr>
            @endif
        </tbody>
    </table>

    <div class="footer">
        Generated by CB Procurement System
    </div>

</body>

</html>